using Cuadrilateros__clase_16.Clases;
Console.WriteLine("INSTANCIAMOS EL CUADRADO");
Punto A=new Punto();Punto B =new Punto();Punto C =new Punto();Punto D =new Punto();
A.X = 0; A.Y = 4;B.Y=4;B.X=3;C.Y=1;C.X=3; D.Y = 1; D.X = 0;
Cuadrilatero.Cuadrado CUADRADO1 = new Cuadrilatero.Cuadrado(A,B,C,D);
Console.WriteLine($"Los puntos son A({A.X},{A.Y}) | B({B.X},{B.Y}) | C({C.X},{C.Y}) | D({D.X},{D.Y})");
Console.WriteLine($"El area es: {CUADRADO1.CalcularArea()}");
Console.WriteLine("---------------------------------------------------------------------------------");
Console.WriteLine("INSTANCIAMOS EL Rectangulo");
A.X = -1; A.Y = 4; B.Y = 4; B.X = 3; C.Y = 1; C.X = 3; D.Y = 1; D.X = -1;
Cuadrilatero.Rectangulo Rectangulo1 = new Cuadrilatero.Rectangulo(A, B, C, D);
Console.WriteLine($"Los puntos son A({A.X},{A.Y}) | B({B.X},{B.Y}) | C({C.X},{C.Y}) | D({D.X},{D.Y})");
Console.WriteLine($"El area es: {Rectangulo1.CalcularArea()}");
Console.WriteLine("---------------------------------------------------------------------------------");
Console.WriteLine("INSTANCIAMOS EL trapecio");
A.X = -1; A.Y = 4; B.Y = 4; B.X = 3; C.Y = 1; C.X = 4; D.Y = 1; D.X = -2;
Cuadrilatero.Trapecio trapecio1 = new Cuadrilatero.Trapecio(A, B, C, D);
Console.WriteLine($"Los puntos son A({A.X},{A.Y}) | B({B.X},{B.Y}) | C({C.X},{C.Y}) | D({D.X},{D.Y})");
Console.WriteLine($"El area es: {trapecio1.CalcularArea()}");
Console.WriteLine("---------------------------------------------------------------------------------");